---
dist: xenial

language: python

# this stops travis from building both pushes and PRs for pr-destined branches
branches:
  only:
    - master
    - /^travis/
    - /^v.*/

cache:
  pip: true

stages:
  - name: test
  - name: deploy docker
  - name: deploy pypi
    if: tag IS present

jobs:
  include:
#    - stage: test
#      python: 3.6
#      install: pip install tox tox-travis
#      script: tox
#
#    - stage: test
#      python: 3.7
#      install: pip install tox tox-travis
#      script: tox
#
#    - stage: test
#      python: 3.8
#      install: pip install tox tox-travis coveralls
#      script: tox
#      after_success: coveralls

    - stage: deploy docker
      python: 3.7
      env:
        - DOCKER_IMAGE=stodevx/stograde
      before_install:
        - sudo apt-get install qemu-user-static -y
        - sudo rm -rf /var/lib/apt/lists/*
        - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) edge"
        - sudo apt-get update
        - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
        - mkdir -vp ~/.docker/cli-plugins/
        - curl --silent -L "https://github.com/docker/buildx/releases/download/v0.4.2/buildx-v0.4.2.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
        - chmod a+x ~/.docker/cli-plugins/docker-buildx
        - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        - docker buildx create --name stogradebuilder
        - docker buildx inspect stogradebuilder --bootstrap
        - docker buildx use stogradebuilder
      script: skip
      deploy:
        - provider: script
          script: script/docker-deploy Dockerfile

    - stage: deploy docker
      python: 3.7
      env:
        - DOCKER_IMAGE=stodevx/stograde
      before_install:
        - sudo apt-get install qemu-user-static -y
        - sudo rm -rf /var/lib/apt/lists/*
        - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) edge"
        - sudo apt-get update
        - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
        - mkdir -vp ~/.docker/cli-plugins/
        - curl --silent -L "https://github.com/docker/buildx/releases/download/v0.4.2/buildx-v0.4.2.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
        - chmod a+x ~/.docker/cli-plugins/docker-buildx
        - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        - docker buildx create --name stogradebuilder
        - docker buildx inspect stogradebuilder --bootstrap
        - docker buildx use stogradebuilder
      script: skip
      deploy:
        - provider: script
          script: script/docker-deploy Dockerfile.gcc "-gcc"

    - stage: deploy pypi
      python: 3.7
      script: skip
      deploy:
        provider: pypi
        user: "hawkrives"
        password: { secure: 'kxjTndHBVztrPi1k74zsL2cjbFrBXe5af0HDn/t4w6CUj0yCf0VPwzR0KnOU6CrvRpMxid7MINsgdh3MsOsgnLiLiQ4TSRqEfB9lsmCopDXArNiC5jq0QmZ1P2KHKguJpkWx8TnwjiJycm1UFJU3l4YRfj5Zo4LvpI/64EUoNhICbf2gAQav8Sb2a9/Ov5hpySBYhmwr/tkODOfZS5+00SAs/OP7bU0xQFhUUwnEY4uAiaTIo+tIOIXx/nwj7XundCEwFXiFDYSEKbk+maHWgUIqbZivL94RigVwTds0KJmpurU1Nc670ggGwT96WcCtNZoMTxB47fXoNqzhTAgp2O2C4lsv1xNIrwSdHzyP20wsDQn3zdMz4aJEfSZMwhvN/GJyQFTKbeD++ysRsfUuI5uQho7BOsGMLDfnDOpncNNXI2zKnea9OStsj/u/aJGNmWFcGa70/CHBeSI9Zmv6Og3KY6fGM28bqQUvO6iFDho98xOTHk+vTIcGyut5DDMuKvQh3ISPYZkz7lSqHqDayXr/RxombkpEPszqlUkn2OO38PLujYJzL8nLUN1g/2m2M4y9h6pXV27sU6hDo0E9WTtRhAA04JqpsJ2S8smw2C+yo446klaMNxUkYbxm4j9PI7pYpLWsqlOMbnCz79PSGuzB17ezk6nr8T22TR0Ci2w=' }
        on: { tags: true }
