---
dist: xenial

language: python

# this stops travis from building both pushes and PRs for pr-destined branches
branches:
  only:
    - master
    - /^travis/
    - /^v.*/

cache:
  pip: true

env:
  - secure: "j2lYO/8l/+RwsYVU4w3HtgJ/aMgMMrrjxi6JZg9/tNPPsukZOvwhzng5i0fpBs5LtBrhXyV9VYmtHx+1tb0ywWW2I3oM/m+ry0dvy01mQWSP5NjW8GSL0RCWP9ZNT8IT95YxdLB8TVQsPOgriluf5JVxwpxfeTu124FR8i+1QAIrfUDhN8AzN2IikP3Zbc1YdBWZP1RkN1dafk2Kwfh32J2K58c5RRx1gNWmw0AmTXXhP+dKjaPS6yKwe+LzxUSHmW1ZX8QA989aINhyJHaoKHi1UPKFotO3jcR1xlPIBuq1OgeVj789hq8yeUoeXbhsHS2x43YkQiNKrmQB6/v0e/oEaAnqRGGo9C8n9z6YgqFgnDdnrAPdy+DAEvKazbAWOwEBLD2dtveBYIVBr4InmQYh0sRHE0HEQXj3kIB2LHguidzjCx96Go7Quof82jF6uhv1uO7y9zU+UbGV+qjkglAxJyeOb6ThqPneA1MJKmKm6uVM2g8sbjQ1DpynXPSCINdS4ZW+EyBlnvVKaLl1x9rZ+t/v+M7roLRxll4BfwgNdHvM0m0ch5dLtny1Q2KUNRMtMsP0F52LRrd7f58VpJeUAD8/zmBp3lNVOQhINoWeH9K9XQMIpeZs2cfkFMm2a7qynrUpqlYdVYRxDtmyDqDUCRXJbWgg5xPf6stZ2Y4="

stages:
  - name: test
  - name: deploy docker
  - name: deploy pypi
    if: tag IS present

jobs:
  include:
    - stage: test
      python: 3.6
      install: pip install tox tox-travis
      script: tox

    - stage: test
      python: 3.7
      install: pip install tox tox-travis
      script: tox
   
    - stage: test
      python: 3.8
      install: pip install tox tox-travis coveralls
      script: tox
      after_success: coveralls

    - stage: deploy docker
      python: 3.7
      services:
        - docker
      env:
        - DOCKER_IMAGE=stodevx/stograde
      script:
        - docker build -t $DOCKER_IMAGE:$TRAVIS_COMMIT -f Dockerfile .
      deploy:
        - provider: script
          script: script/docker-deploy $DOCKER_IMAGE:$TRAVIS_COMMIT $DOCKER_IMAGE:HEAD
          on: { branch: 'master' }
        - provider: script
          script: script/docker-deploy $DOCKER_IMAGE:$TRAVIS_COMMIT $DOCKER_IMAGE:$TRAVIS_TAG
          on: { tags: true }
        - provider: script
          script: script/docker-deploy $DOCKER_IMAGE:$TRAVIS_COMMIT $DOCKER_IMAGE:latest
          on:
            tags: true
            condition: $(script/github-latest-release) == $TRAVIS_TAG
        - provider: script
          script: script/docker-deploy $DOCKER_IMAGE:$TRAVIS_COMMIT $DOCKER_IMAGE:$TRAVIS_COMMIT
          on: { branch: 'travis-*' }

    - stage: deploy docker
      python: 3.7
      services:
        - docker
      env:
        - DOCKER_IMAGE=stodevx/stograde
      script:
        - docker build -t $DOCKER_IMAGE:$TRAVIS_COMMIT -f Dockerfile.gcc .
      deploy:
        - provider: script
          script: script/docker-deploy $DOCKER_IMAGE:$TRAVIS_COMMIT $DOCKER_IMAGE:HEAD-gcc
          on: { branch: 'master' }
        - provider: script
          script: script/docker-deploy $DOCKER_IMAGE:$TRAVIS_COMMIT $DOCKER_IMAGE:$TRAVIS_TAG-gcc
          on: { tags: true }
        - provider: script
          script: script/docker-deploy $DOCKER_IMAGE:$TRAVIS_COMMIT $DOCKER_IMAGE:latest-gcc
          on:
            tags: true
            condition: $(script/github-latest-release) == $TRAVIS_TAG
        - provider: script
          script: script/docker-deploy $DOCKER_IMAGE:$TRAVIS_COMMIT $DOCKER_IMAGE:$TRAVIS_COMMIT-gcc
          on: { branch: 'travis-*' }

    - stage: deploy pypi
      python: 3.7
      script: skip
      deploy:
        provider: pypi
        user: "hawkrives"
        password: { secure: 'kxjTndHBVztrPi1k74zsL2cjbFrBXe5af0HDn/t4w6CUj0yCf0VPwzR0KnOU6CrvRpMxid7MINsgdh3MsOsgnLiLiQ4TSRqEfB9lsmCopDXArNiC5jq0QmZ1P2KHKguJpkWx8TnwjiJycm1UFJU3l4YRfj5Zo4LvpI/64EUoNhICbf2gAQav8Sb2a9/Ov5hpySBYhmwr/tkODOfZS5+00SAs/OP7bU0xQFhUUwnEY4uAiaTIo+tIOIXx/nwj7XundCEwFXiFDYSEKbk+maHWgUIqbZivL94RigVwTds0KJmpurU1Nc670ggGwT96WcCtNZoMTxB47fXoNqzhTAgp2O2C4lsv1xNIrwSdHzyP20wsDQn3zdMz4aJEfSZMwhvN/GJyQFTKbeD++ysRsfUuI5uQho7BOsGMLDfnDOpncNNXI2zKnea9OStsj/u/aJGNmWFcGa70/CHBeSI9Zmv6Og3KY6fGM28bqQUvO6iFDho98xOTHk+vTIcGyut5DDMuKvQh3ISPYZkz7lSqHqDayXr/RxombkpEPszqlUkn2OO38PLujYJzL8nLUN1g/2m2M4y9h6pXV27sU6hDo0E9WTtRhAA04JqpsJ2S8smw2C+yo446klaMNxUkYbxm4j9PI7pYpLWsqlOMbnCz79PSGuzB17ezk6nr8T22TR0Ci2w=' }
        on: { tags: true }
